version: "3.9"

services:

  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - vol_wordpress:/var/www/html/wordpress
    networks:
      - net_inception
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - vol_mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net_inception
    restart: always
    

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - vol_wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - net_inception
    depends_on:
      - mariadb
    restart: always

volumes:

  vol_mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/bsavinel/data/vol_mariadb
      o: bind
    
  vol_wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/bsavinel/data/vol_wordpress
      o: bind

networks:
  net_inception:
    driver: bridge