version: "3.9"

service:

  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - docker-network
    restart: always

  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - docker-network
    restart: always
    

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    networks:
      - docker-network
    restart: always
    env_file:
      - .env

networks:
  docker-network:
    driver: bridge